name: Laravel CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

        # - name: Install Composer Dependencies
        # run: composer install --no-interaction --prefer-dist --no-progress
        # composer install --no-dev --optimize-autoloader


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            whoami
            echo $HOME

            sudo -i <<'EOF'
            whoami
            echo $HOME

            cd /var/www/learning_devops_workflow

            git status
            git branch -vv
            git remote -v

            git fetch origin

            echo "HEAD:"
            git rev-parse HEAD

            echo "ORIGIN:"
            git rev-parse origin/master

            git pull origin master

            echo "AFTER PULL:"
            git rev-parse HEAD

            php artisan migrate --force
            php artisan optimize:clear

            systemctl restart apache2
            EOF